version: '3.8'

services:
  backend:
    build: ./backend
    container_name: rate_limiter_backend
    ports:
      - "8000:8000"
    networks:
      - rate_limiter_network

  api_gateway:
    build: ./api_gateway
    container_name: rate_limiter_gateway
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - rate_limiter_network

networks:
  rate_limiter_network:
    driver: bridge
